<a href="https://colab.research.google.com/github/Gitumbu95/array/blob/main/Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

One Dimension Arrays (1-D)

In [10]:
#packages
import numpy as np

#Arrays- stores values of the same type
#np.arange(stop)
arr1 = np.arange(9) #9 reps the stop value
print(arr1, type(arr1))

#np.arange(start, stop)
arr2= np.arange(2, 10) #2- start value, 10-stop value
print(arr2, type(arr2))

#np.arange(start, stop, step)
arr3= np.arange(1, 10, 2) #odd values
print(arr3, type(arr3))

arr4= np.arange(-1, 11.7, 2.5) #floating point step
print(arr4, type(arr4))

[0 1 2 3 4 5 6 7 8] <class 'numpy.ndarray'>
[2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[1 3 5 7 9] <class 'numpy.ndarray'>
[-1.   1.5  4.   6.5  9.  11.5] <class 'numpy.ndarray'>


In [31]:
#arrays from the lists
from_list = np.array([1,4,7, 0])
print(from_list)
print(type(from_list[1])) #checking the data type of an element.

from_list1 = np.array([1,4,7, 0], dtype=np.int8) #assinging datatype to the array for memory efficiency
print(type(from_list1[2]))
print("Shape:", from_list1.shape)

[1 4 7 0]
<class 'numpy.int64'>
<class 'numpy.int8'>
Shape: (4,)


Two Dimensional Arrays (2-D)

In [35]:
arr= np.array([[1,2,3,],[5,6,7]], dtype=np.int8) #list
print(arr, type(arr))

arr2= np.array((np.arange(0,8,2), np.arange(1,8,2)), dtype=np.int8)
print(arr2, type(arr2))
print("Shape:", arr2.shape)

#reshaping array
n_arr2= arr2.reshape(4,2)
print(n_arr2, n_arr2.shape)

[[1 2 3]
 [5 6 7]] <class 'numpy.ndarray'>
[[0 2 4 6]
 [1 3 5 7]] <class 'numpy.ndarray'>
Shape: (2, 4)
[[0 2]
 [4 6]
 [1 3]
 [5 7]] (4, 2)


In [47]:
#empty arrays
zeros= np.zeros((3,3))
print(zeros)
print(zeros.shape)

ones= np.ones((2,2))
print(ones)
print(ones.shape)

random= np.empty((1,3,4)) #retuns random values
print(random)
print(random.shape)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
[[1. 1.]
 [1. 1.]]
(2, 2)
[[[5.06350005e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]]
(1, 3, 4)
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [55]:
#diagonal matrix
eye = np.eye(5, k=1)
eye[eye == 0] = 3 #filtering and replacing
eye[eye <= 1] =4

#filtering rows and columns
eye[0:2]= 5 #rows
eye[:, 2] = 7 #columns
eye[:, -1] = 9 #columns
print(eye)

[[5. 5. 7. 5. 9.]
 [5. 5. 7. 5. 9.]
 [3. 3. 7. 4. 9.]
 [3. 3. 7. 3. 9.]
 [3. 3. 7. 3. 9.]]


Sorting Arrays

In [60]:
#default sort (kind= quicksort); heapsort
#sorting by rows
print(eye, "\n")
sort_eye=np.sort(eye)
print(sort_eye, "\n")

#sorting by columns
sortcol = np.sort(eye, axis=0, kind="mergesort")
print(sortcol)

[[5. 5. 7. 5. 9.]
 [5. 5. 7. 5. 9.]
 [3. 3. 7. 4. 9.]
 [3. 3. 7. 3. 9.]
 [3. 3. 7. 3. 9.]] 

[[5. 5. 5. 7. 9.]
 [5. 5. 5. 7. 9.]
 [3. 3. 4. 7. 9.]
 [3. 3. 3. 7. 9.]
 [3. 3. 3. 7. 9.]] 

[[3. 3. 7. 3. 9.]
 [3. 3. 7. 3. 9.]
 [3. 3. 7. 4. 9.]
 [5. 5. 7. 5. 9.]
 [5. 5. 7. 5. 9.]]


Copying Array

In [70]:

#making copys of arrays
#view method (modifies the original array)
arr_view= sortcol.view()
arr_view[1:3] = 8
print(arr_view , "\n")

print(sortcol, "\n")
#copy method- doesn't alter with the original array
arr_copy =sortcol.copy()
arr_copy[3:-1] = 2
print(arr_copy)




[[3. 3. 7. 3. 9.]
 [8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]
 [5. 5. 7. 5. 9.]
 [5. 5. 7. 5. 9.]] 

[[3. 3. 7. 3. 9.]
 [8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]
 [5. 5. 7. 5. 9.]
 [5. 5. 7. 5. 9.]] 

[[3. 3. 7. 3. 9.]
 [8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]
 [2. 2. 2. 2. 2.]
 [5. 5. 7. 5. 9.]]


Array Operations


In [101]:
a = np.ones((3,3), dtype=np.int8)
a[2] = 2
a[1].fill(3)
a[0] *= 4 #/= += -=
print(a,"\n", a.dtype)


b= np.arange(0,9, dtype = np.int8).reshape(3,3)
print(b, "\n", b.dtype)


[[4 4 4]
 [3 3 3]
 [2 2 2]] 
 int8
[[0 1 2]
 [3 4 5]
 [6 7 8]] 
 int8


Arithmetic Operations

In [103]:
#summation
sum_a = a.sum() #entire array
sum_col= b.sum(axis = 0) #sum per column
sum_row = b.sum(axis =1) #sum per row
print(sum_a)
print(sum_col)
print(sum_row)

27
[ 9 12 15]
[ 3 12 21]


In [110]:
#Product/ multiplicataion
prod_array = a.prod() #all elements of the array
prod_col = b.prod(axis=0) #column elements
prod_row = a.prod(axis=1) #row elements
print(prod_array)
print(prod_col)
print(prod_row)



13824
[ 0 28 80]
[64 27  8]


In [121]:
#mean of an array
average_a = a.mean()
print(average_a)

#max and min
mina= b.min()
maxa = b.max()
print("Min:", mina, "Max:", maxa)

#min and max by index
minb =a.argmin()
maxb =a.argmax()
print(minb, maxb)

#peak-to-peak
peak = a.ptp() #returns max - min
print(peak)

3.0
Min: 0 Max: 8
6 0
2


In [133]:
#flatten array(convert to 1D array)
flat = a.reshape(a.size)
print(flat)
flat_b= b.flatten() #makes copy of original array
print(flat_b)
flat_a = a.ravel() #creates a view of array ie alters the original array
print(flat_a)

#repeat arrays /value
rep = np.repeat(10, 3) # values
print(rep)
rep_ar = np.repeat(b, 2, axis= 1)
print(rep_ar)

#unique
uni =np.unique(rep_ar)
print(uni)

#fetching the major diagonal values of the array
diag = np.diagonal(b, offset= -1)
print(diag)

[4 4 4 3 3 3 2 2 2]
[0 1 2 3 4 5 6 7 8]
[4 4 4 3 3 3 2 2 2]
[10 10 10]
[[0 0 1 1 2 2]
 [3 3 4 4 5 5]
 [6 6 7 7 8 8]]
[0 1 2 3 4 5 6 7 8]
[3 7]


In [137]:
#conversion and storage
#array to list
con= b.tolist()
print(con, type(con))

#array to file
file= a.tofile( "array_file.txt",sep=",")
print(file)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]] <class 'list'>
None


In [142]:
#transposition (same concept as transposing a matrix)
trans = np.swapaxes(b, 0, 1)
print(trans)

transpose = b.transpose(1, 0)
print(transpose)

T=b.T
print(T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


Operations on matrices

In [158]:
#summation
sum = a + b
print(sum)

#substraction
sub = a - b
print(sub)

#modulo
mod = b % a
print(mod)

#float division rounds the fraction to the nearest whole numbers
flo = b // a #retuns integers
print(flo)

npflo = np.floor(b/a) #returns whole numbers but of type float
print(npflo)

#multiplication #element wise multiplication
prod= a * b
print(prod)

#matrix multiplication #matrix wise multiplication
mat_mul =np.matmul(a,b)
print(mat_mul)

mat_dot = a.dot(b)
print(mat_dot)

at = a @ b
print(at)


[[ 4  5  6]
 [ 6  7  8]
 [ 8  9 10]]
[[ 4  3  2]
 [ 0 -1 -2]
 [-4 -5 -6]]
[[0 1 2]
 [0 1 2]
 [0 1 0]]
[[0 0 0]
 [1 1 1]
 [3 3 4]]
[[0. 0. 0.]
 [1. 1. 1.]
 [3. 3. 4.]]
[[ 0  4  8]
 [ 9 12 15]
 [12 14 16]]
[[36 48 60]
 [27 36 45]
 [18 24 30]]
[[36 48 60]
 [27 36 45]
 [18 24 30]]
[[36 48 60]
 [27 36 45]
 [18 24 30]]
